export const PRODUCTS_BASE_PATH = 'products';

export const PRODUCTS_PATHS = {
    GET_ALL: '',
    GET_BY_ID: ':id',
    CREATE: '',
    UPDATE: '',
    DELETE: ':id'
};

export const PRODUCTS_ENDPOINTS = {
    GET_ALL: `${PRODUCTS_BASE_PATH}/${PRODUCTS_PATHS.GET_ALL}`,
    GET_BY_ID: `${PRODUCTS_BASE_PATH}/${PRODUCTS_PATHS.GET_BY_ID}`,
    CREATE: `${PRODUCTS_BASE_PATH}/${PRODUCTS_PATHS.CREATE}`,
    UPDATE: `${PRODUCTS_BASE_PATH}/${PRODUCTS_PATHS.UPDATE}`,
    DELETE: `${PRODUCTS_BASE_PATH}/${PRODUCTS_PATHS.DELETE}`
}; 