export const AUTH_BASE_PATH = 'auth';

export const AUTH_PATHS = {
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-up',
  CONFIRM_SIGN_UP: 'confirm-sign-up',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_PASSWORD: 'reset-password',
  SIGN_OUT: 'sign-out',
  CHANGE_PASSWORD: 'change-password',
  CHANGE_EMAIL: 'change-email',
  CONFIRM_CHANGE_EMAIL: 'confirm-change-email',
  RESEND_CODE: 'resend-code',
  VALIDATE_PASSWORD: 'validate-password'
};

export const AUTH_ENDPOINTS = {
  SIGN_IN: `${AUTH_BASE_PATH}/${AUTH_PATHS.SIGN_IN}`,
  SIGN_UP: `${AUTH_BASE_PATH}/${AUTH_PATHS.SIGN_UP}`,
  CONFIRM_SIGN_UP: `${AUTH_BASE_PATH}/${AUTH_PATHS.CONFIRM_SIGN_UP}`,
  FORGOT_PASSWORD: `${AUTH_BASE_PATH}/${AUTH_PATHS.FORGOT_PASSWORD}`,
  RESET_PASSWORD: `${AUTH_BASE_PATH}/${AUTH_PATHS.RESET_PASSWORD}`,
  SIGN_OUT: `${AUTH_BASE_PATH}/${AUTH_PATHS.SIGN_OUT}`,
  CHANGE_PASSWORD: `${AUTH_BASE_PATH}/${AUTH_PATHS.CHANGE_PASSWORD}`,
  CHANGE_EMAIL: `${AUTH_BASE_PATH}/${AUTH_PATHS.CHANGE_EMAIL}`,
  CONFIRM_CHANGE_EMAIL: `${AUTH_BASE_PATH}/${AUTH_PATHS.CONFIRM_CHANGE_EMAIL}`,
  RESEND_CODE: `${AUTH_BASE_PATH}/${AUTH_PATHS.RESEND_CODE}`,
  VALIDATE_PASSWORD: `${AUTH_BASE_PATH}/${AUTH_PATHS.VALIDATE_PASSWORD}`
};
